// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Db$ReasonDb = require("../src/Db.bs.js");

var me = {
  id: 0,
  name: "alex"
};

Db$ReasonDb.add({
      TAG: /* Person */0,
      _0: me
    });

var getMe = {
  TAG: /* Person */0,
  _0: me
};

console.log(Db$ReasonDb.getPerson(0));

exports.me = me;
exports.getMe = getMe;
/*  Not a pure module */
