// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Future = require("reason-future/src/Future.bs.js");

function add() {
  return Future.make((function (resolve) {
                return setTimeout((function () {
                              return Curry._1(resolve, /* Ok */Block.__(0, [/* () */0]));
                            }), 2000);
              }));
}

exports.add = add;
/* No side effect */
