// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Future = require("reason-future/src/Future.bs.js");
var Db$ReasonDb = require("./Db.bs.js");

Future.tapError(Future.tapOk(Db$ReasonDb.add(/* record */[
              /* id */1,
              /* name */"hannibal"
            ], Db$ReasonDb.store), (function (m) {
            console.log(m);
            return /* () */0;
          })), (function (err) {
        console.log("Something went wrong :(");
        console.log(err);
        return /* () */0;
      }));

/*  Not a pure module */
