// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var Db$ReasonDb = require("../src/Db.bs.js");

Jest.test("To store a Person", (function (param) {
        Db$ReasonDb.add({
              TAG: /* Person */0,
              _0: {
                id: 0,
                name: "alex"
              }
            });
        return Jest.Expect.toEqual(true, Jest.Expect.expect(true));
      }));

/*  Not a pure module */
