// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Block = require("bs-platform/lib/js/block.js");
var Db$ReasonDb = require("../src/Db.bs.js");

Jest.test("To store a Person", (function (param) {
        var me = /* record */[
          /* id */0,
          /* name */"alex"
        ];
        Db$ReasonDb.add(/* Person */Block.__(0, [me]));
        return Jest.Expect[/* toEqual */12](/* Person */Block.__(0, [me]), Jest.Expect[/* expect */0](Db$ReasonDb.getPerson(0)));
      }));

/*  Not a pure module */
